[unstable]
build-std = ["std", "panic_abort"]

[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
# Optionnel : activez-le si vous utilisez l'outil de flash espflash en runner
# runner = "espflash flash --monitor"
rustflags = [
    "-C", "default-linker-libraries",
]

[env]
# Indique à esp-idf-sys pour quel microcontrôleur compiler
MCU = "esp32s3"
# Version stable d'ESP-IDF recommandée pour l'ESP32-S3
ESP_IDF_VERSION = "v5.2.1"
