[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["-C", "default-linker-libraries"]

[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32"
